"""user movie rating

Revision ID: 20225d43bf7a
Revises: 
Create Date: 2020-11-12 00:08:14.885664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20225d43bf7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('movieid', sa.Integer(), nullable=False),
    sa.Column('movielensid', sa.Integer(), nullable=True),
    sa.Column('imdbid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('plot', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('movieid')
    )
    op.create_index(op.f('ix_movie_imdbid'), 'movie', ['imdbid'], unique=True)
    op.create_index(op.f('ix_movie_movielensid'), 'movie', ['movielensid'], unique=True)
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('user_movie_rating',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('movieid', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['movieid'], ['movie.movieid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('userid', 'movieid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movie_rating')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_index(op.f('ix_movie_movielensid'), table_name='movie')
    op.drop_index(op.f('ix_movie_imdbid'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
